### ISSUE TITLE
[BUG] console error 

### ISSUE THREAD

**Issue by Dancbeunny98** [imDaniX/ReActions#1]
**Опишите баг**
При старте сервера выскакивает ошибка. (Ядро Spigot 1.14.4 сборка 2423 даты 26.07.19)

**Лог**
```
> [15:46:29] [Server thread/INFO]: [ReActions] Enabling ReActions v0.12.10
> [15:46:29] [Server thread/ERROR]: Error occurred while enabling ReActions v0.12.10 (Is it up to date?)
java.lang.NoClassDefFoundError: me/fromgate/reactions/activators/ActivatorType
at me.fromgate.reactions.util.message.Msg.testRequiredMessages(Msg.java:754) ~[?:?]
at me.fromgate.reactions.util.message.Msg.init(Msg.java:724) ~[?:?]
at me.fromgate.reactions.ReActions.onEnable(ReActions.java:67) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-1981d55-3e7b386]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot.jar:git-Spigot-1981d55-3e7b386]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot.jar:git-Spigot-1981d55-3e7b386]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot.jar:git-Spigot-1981d55-3e7b386]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot.jar:git-Spigot-1981d55-3e7b386]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot.jar:git-Spigot-1981d55-3e7b386]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot.jar:git-Spigot-1981d55-3e7b386]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:774) [spigot.jar:git-Spigot-1981d55-3e7b386]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: me.fromgate.reactions.activators.ActivatorType
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot.jar:git-Spigot-1981d55-3e7b386]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot.jar:git-Spigot-1981d55-3e7b386]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
... 12 more
```

Не забывайте в релиз собранный плагин кидать. ок?

**Comment by imDaniX** [comment]
Весьма странно. Ошибка появляется всегда при старте сервера?
По поводу релизов - не уверен в надобности, по крайней мере сейчас. Все билды доступны для скачивания на [CircleCI](https://circleci.com/gh/imDaniX/ReActions).

**Comment by Dancbeunny98** [comment]
Обновил до последнего вашего билда. Ошибка пропала. Продолжайте усовершенствовать данный плагин!
